### PR TITLE
Visualization of pcd and rgb along with posenet

### PR DESCRIPTION
**Pull request by prajurock**
Work item :-[Evaluate PersonLab feet/face visibility vs. error of results](https://dev.azure.com/cgmwhh/ChildGrowthMonitor/_workitems/edit/1758/
)
Work done
best / worst examples are  visualized
both the images for pose prediction and
the artifacts (pcd) for result generation

### CODE REVIEW

**Comment by markus-hinsche** [comment]
Looks good

There are some possibilities to improve the readability of your code: Maybe you can use the flake8/pep8 style, which is what most python developers stick to.

**Review by markus-hinsche — APPROVED** [review]

**Comment by prajurock** [comment]
@markus-hinsche  improved the code style ready to merge.

**Comment by markus-hinsche** [comment]
Cool, looks good. I can give more feeback in next review

**Comment by prajurock** [comment]
Thank you. That will be really helpful

**Pull request merged**
