### PR TITLE
Create dataset for angle analysis

### PR DESCRIPTION
**Pull request by markus-hinsche**
CR: https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1289

**Changes:**
- Document how to interpret angle
- add angle to mlpipeline as metadata
- Simplify how angle is being calculated
- Revert angle (solve TODO comment) to avoid failure when the center pixel is invalid

### CODE REVIEW

**Comment by lvonasek** [comment]
@markus-hinsche Please wait with merging, I found there is a mistake in the angle formula. I am going to fix that

**Comment by lvonasek** [comment]
Now it works correctly.

Tested using:
* run CV/evaluation.py
* sort output.py by the angle (using LibreOffice)
* run CV/renderer.py
* check the visualisations are ordered by angle

Maximal value in raw dataset: -16° (slightly pointing down on a child):

Minimal value in raw dataset: -87° (the child from topdown):

**Review by lvonasek — APPROVED** [review]
LGTM

**Comment by markus-hinsche** [comment]
Great simplification!

**Pull request merged**
