### PR TITLE
Analyse the pose estimation model output

### PR DESCRIPTION
**Pull request by cishwarya**
**Summary of change:**
The change refers to the newly added script "analyseOutput.py" under the directory, cgm-ml/src/common/reliability/pose_estimation/analysis
The script, "analyseOutput.py" is used to analyse the pose estimation model output.

**Background:**
The pretrained CAFFE Pose estimation model is run on (1/6)th of the samples from the "anon_RGB_training dataset" and 
the results are stored in "<pose_estimation_output>.json". As the json file is huge this could not be uploaded in git.  
In order to create the json file, please run the Pose estimation notebook located in the directory. "src/common/reliability/pose_estimation/QA/poseest_notebook.ipynb" 

**Prerequisites and dependencies:**
Following files are required to run analyseOutput.py and these have been added in the same directory.

1. config.py 
2. posepoints.py 
3. < pose_estimation_output >.json 

Required library to run analyseOutput.py:

- pandas

Results of the pose estimation model is saved as a json file. This is given as input to analyseOutput.py.
Configuration details such as model and dataset type used by the pose estimation model is saved in config.py.
To know more details about the pose estimation models, please refer: https://www.learnopencv.com/deep-learning-based-human-pose-estimation-using-opencv-cpp-python/

**Tests:**
Tests have been carried on different samples of data and results have been verified. 
Please refer to SampleOutput.txt for a sample output.

To reproduce the results please specify the following:

1. Path of the json file must be defined in the function "load_json" in analyseOutput.py
2. The number of images used for finding the pose points needs to be species in the variable <num_qrcodes> in analyseOutput.py
3. config.py file should have the relevant parameter values for DATASETTYPE_PATH and MODELTYPE_PATH

**Code review:**
Style guidelines have been followed and it has been verified with flake8 library
The code has been reviewed and necessary comments have been added to make it self-explanatory

### CODE REVIEW

**Comment by markus-hinsche** [comment]
Thanks a lot for the contribution

A couple of first comments:
- please remove large files (Your zip file has several megabytes, so this does not belong into git)
- please notice the checks of this PR indicate that there are remaining flake8 issues

**Review by cishwarya — COMMENTED** [review]
Self review completed

**Review by cishwarya — COMMENTED** [review]
Self review completed

**Comment by cishwarya** [comment]
> Thanks a lot for the contribution
> 
> A couple of first comments:
> 
> * please remove large files (Your zip file has several megabytes, so this does not belong into git)
> * please notice the checks of this PR indicate that there are remaining flake8 issues

Hello Markus, 
thanks very much for your reply. 
I have corrected the code and it has successfully passed the tests.

**Comment by cishwarya** [comment]
By mistake I have closed the pull request.
Have reopened it.

**Comment by markus-hinsche** [comment]
Hi @cishwarya, thanks for the changes. 
So I understand that you have some Caffe model. Please explain 
- how to get this Caffe model
- how to setup the model
- how to download the dataset
- how to run the evaluation to evaluate this model

Basically if I would like to run this experiment that you did, what are the steps I have to do?

**Comment by cishwarya** [comment]
Dear Markus,

The Caffe Pose estimation model has been executed by the user Pankaja0285 (Pankaja Shankar) . She has added her code in PR #205 .

She should be able to give you more details on how to setup the dataset and run the model. I am unable to add her to this comment. Could you please comment on her PR .

Once this caffe model is run, the output will be saved in the json format. 

My analysis is based on this file, for which I have explained how to run my script in the description.

If you need some help please let me know.

Thank you

**Comment by markus-hinsche** [comment]
@cishwarya Great, I left some comments in the PR #205. Let's see if @pankaja0285 will answer, maybe you two can get in touch. Thank you

**Comment by markus-hinsche** [comment]
This was merged to our codebase. Thanks for the contribution

**Pull request merged**
