### PR TITLE
CI is Failed in recent commit

### PR DESCRIPTION
**Pull request by prajurock**
# Description

Ci is failing due to a cache error.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests
- [x] New and existing unit tests pass locally with my changes
- [x] My Code is review by 1 People

### CODE REVIEW

**Comment by lvonasek** [comment]
Did this happen due to a change in requirements.txt? If yes, could we add a comment into the file that on change also CI.yml has to be updated?

**Comment by prajurock** [comment]
Yes. We can do that. Thanks @lvonasek

**Comment by lvonasek** [comment]
> Yes. We can do that. Thanks, @lvonasek . Where I should put the comment? can you suggest?

I would suggest on the first line of requirements.txt:
# on updating dependencies please also update cache version in CI config file (e.g. https://github.com/Welthungerhilfe/cgm-ml/pull/489/files)

**Review by lvonasek — APPROVED** [review]
LGTM, thanks for fixing this :)

**Pull request merged**
