### PR TITLE
Un-deprecate ResNet model #325

### PR DESCRIPTION
**Pull request by jasminziegler**
# Description

#325 Un-deprecate ResNet model (see description in issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] My Code is review by 1 People

### CODE REVIEW

**Comment by jasminziegler** [comment]
@prajurock idk why import is not working. I copied everything over from plaincnn folder, created 2 __init__.py files, do I still need to set some environment vars? So the package can be found?

**Comment by prajurock** [comment]
> @prajurock idk why import is not working. I copied everything over from plaincnn folder, created 2 **init**.py files, do I still need to set some environment vars? So the package can be found?

Hi @jasminziegler  Can you change the path file location into src. That will resolve the issue

**Comment by markus-hinsche** [comment]
Did you achieve the ACs of https://github.com/Welthungerhilfe/cgm-ml/issues/325?

**Review by markus-hinsche — APPROVED** [review]
LGTM

The code looks good. In order to see if the training with resnet will really work we should run the training and notice that it trains for several epochs.

**Comment by markus-hinsche** [comment]
I am working on https://github.com/Welthungerhilfe/cgm-ml/pull/341 which is trying to solve this issue

**Review by markus-hinsche — CHANGES_REQUESTED** [review]
Temporary files are added, the training run is not yet working

**Comment by markus-hinsche** [comment]
Closing in favor of #341

**Pull request closed without merging**
