### PR TITLE
Change testdata so the image moves a little bit

### PR DESCRIPTION
**Pull request by markus-hinsche**
**Motivation:** the test data (3 frames) was not moving, so we could barely see a difference between the frames.

**Solution:** Replace with test data (3 frames) that changes more between frames

### CODE REVIEW

**Comment by lvonasek** [comment]
@markus-hinsche 
I cannot review this PR, the branch does not open on my machine:
$ git checkout mhinsche-change-testdata
error: invalid path 'src/common/data_utilities/tests/pickle_files/scans/c571de02-a723-11eb-8845-bb6589a1fbe8/102/pc_c571de02-a723-11eb-8845-bb6589a1fbe8_2021-04-22 13:34:33.302557_102_3.p'

**Comment by markus-hinsche** [comment]
That's very odd. This file wasn't changed in this PR. 

Ideas:
- Do you have unstashed local changes?
- Does https://stackoverflow.com/a/63742773/5497962 help?

**Comment by lvonasek** [comment]
Calling
git config core.protectNTFS false
git checkout mhinsche-change-testdata
broke my local git repository references but I was able to checkout the branch

**Review by lvonasek — APPROVED** [review]
LGTM

**Pull request merged**
