### PR TITLE
new database schema

### PR DESCRIPTION
**Pull request by mmatiaschek**
image

### CODE REVIEW

**Comment by ZhangNemo34** [comment]
1. Does **measure_result** table store the body parameters (height, weight, muac ...) for scan measurement from ML backend? Why do we need **confidence_value** here?
If **measure_result** table is for scan quality, we won't need this table.
Because scan quality for measure will be calculated from **artifact_result** table as an average of **confidence_value** where **measure_id** is same.

2. **artifact_table** stores the scan quality (lightening score at this moment).
We need to have **scan_step**(100, 101, 102, 200, 201, 202) to calculate score for each step, also measure_id to calculate average score for 1 measure (3 scan steps).
Of course I can retrieve this scan_step, measure_id from artifact table using foreign key, but the best is to save them in artifact_result table for better performance.

3. Don't understand about **new_artifacts** & **new_artifacts_file_size_mb** in **device** table.
Does this mean the new artifacts created from the last device message created?

4. If we have **deleted_artifacts_file_size_mb** in **device** table, it would be good to check uploading speed in MB.

5. Not sure if we should have **own_artifacts** & **ownn_artifacts_file_size_mb** because there are some situations like login to another user's device.
This is really happend with cgm06 recently.

6. I'm not sure which value to save into **float_value** & **json_value** of **artifact_result** & **measure_result** table.

**Comment by AI-Guru** [comment]
I am very optimistic about this pull request!

The JSON data definitely thrills me. This was new to me. JSON integrates very well in PostgreSQL. We can do a lot of fancy queries with that. Should relax a couple of issues we are having.

PostgreSQL and JSON reference: http://www.postgresqltutorial.com/postgresql-json/

Everything seems to be in place when it comes to my ML-perspective. For training, we need the connection between artifacts and measures. Check. And for evaluation/analysis we also need the connections involving measure results, artifact results and model.

Looks very promising, and I would love to see the new DB schema tested in a sprint in the near future.

**Comment by shanky0009** [comment]
Will it be complicated if we have a different table for status like artifact_status(containing artifact_id and status)

**Comment by mmatiaschek** [comment]
This pull request is in a weird state. I'll move the discussion over to DevOps for now.

**Pull request merged**
